Dev timer and btn state
VSerj/Type-faster pull request #10
Opened 2020-12-05 12:56 UTC by VSerj

Если нажать кнопку Start : 
 - кнопка Stop  и выбор времени становятся неактивными ;
- загружается текст ;
- после загрузки текста добавил подсказку ;
- устанавливается слушатель keydown ;
  - если нажать любую клавишу  - запустится обратный таймер;
    - удаляет подсказку.

Если время обратного таймера истекло - возврат в исходное состояние.

Если нажать кнопку Stop:
- удаляет подсказку;
- обратный отсчет прекращается;
- возврат в исходное состояние;

Разработана установка времени в таймер:
 - с эффектом увеличения таймера при установке;
 - также когда время заканчивается;

2020-12-06 06:58 UTC, bringmetheaugust reviewed
требуется обсуждения дискуссий ниже

2020-12-06 06:58 UTC, bringmetheaugust commented on src/js/custom-error.js
> +}
**git** жалуется, что файл не заанчивается на пустую строку

2020-12-06 06:58 UTC, bringmetheaugust commented on src/js/start-stop.js
> +  // пока не покажется текст в поле
если коммент описывает одну строку кода, то пишем коммент в той самой строке кода

2020-12-06 06:58 UTC, bringmetheaugust commented on src/js/start-stop.js
> +  // Для проверки и удаления подсказки, если она активна.
аналогично касательно комментария на одну строку кода

2020-12-06 06:58 UTC, bringmetheaugust commented on src/js/temp-helpers-dev.js
> +// но необходимы для тестирования текущих разработок.
для таких вещей принято создавать файл **utils.js** или целую папку **utils**.
к утилитам относятся вспомогательные методы, которые принимают участие в коде, но не являются основной логикой. например, *метод создание нужного формата даты* или *какое-то частое использование форматирование строки*.
например, метод `createId`:
```
// генерирует случайный ID
function createId() {
    return Math.floor(Math.random() * 100000000); // получим примерно вот такой 94239477287 ID
}
```
этот метод более относиться к вспомагательным методам, чем к главной логики.

так же можно рассортировать утилиты:
* для вспомогательных штук, которые всегда в продакшине подписывать как **utils.js** или папка **utils**
* для *dev/тестирования* подписывать как **dev_utils.js** или папку **dev_utils**

2020-12-06 06:58 UTC, bringmetheaugust commented on src/js/text-from-api.js
> +  states.isLoading = false;
здесь небольшой недочет.
при успешном запросе к **API** у тебя вызывается функция `showText` и срабатывает `states.isLoading = false;`.
но при ошибке (`handleError`),`states.isLoading` продолжает быть `true`.
в итоге прелоадер продолжает работать, а кнопка **Stop** ничего не делает из-за https://github.com/VSerj/Type-faster/blob/fea1f1cfa8376f44e344dd5d03b7615900039981/src/js/start-stop.js#L29.
то есть, тебе нужно `states.isLoading` поставить в `false` **сразу же, когда закончился запрос (независимо какой у него результат)**.
для этого у промисов есть метод `finally`, который выполняется в самом конце промиса (в нашем случае `fetch`) при любых обстоятельствах.

если я что-то не учел, то уточни

2020-12-06 06:58 UTC, bringmetheaugust commented on src/js/timer.js
> +  }
ну тут в одну строку можно было записать условие

2020-12-06 06:58 UTC, bringmetheaugust commented on src/scss/modules/_radio-buttons.scss
> +.radio-buttons.disabled {
здесь не нужно заново писать родительсткий селектор, а надо использовать `&`

2020-12-06 06:58 UTC, bringmetheaugust commented on src/js/makeElem.js
> +export function makeElem({
глагол **make** не совсем подходит))
**create**/**build** более корректнее

2020-12-06 07:02 UTC, bringmetheaugust approved these changes

2020-12-06 07:03 UTC, bringmetheaugust requested changes
пока не надо сливать в **master**

2020-12-06 08:38 UTC, VSerj commented on src/js/custom-error.js
> +}
Помню, что добавлял. Наверно,  где-то снова удалил. Исправим.

2020-12-06 08:40 UTC, VSerj commented on src/js/start-stop.js
> +  // пока не покажется текст в поле
ок

2020-12-06 08:57 UTC, VSerj commented on src/js/temp-helpers-dev.js
> +// но необходимы для тестирования текущих разработок.
Долго не знал куда поместить функцию, без которой не проверить выполнения текущего кода в текущей ветви, а сама функция это уже часть другой логики, которая будет разработана в будущем и не будет  вспомогательной (только в этой текущей ветви).

Как некая временная заглушка. 

Возможно, это не правильный подход к разработке.

Тогда, поместить в дев?

2020-12-06 09:59 UTC, VSerj commented on src/js/text-from-api.js
> +  states.isLoading = false;
`handleError `может запустить `showText` со своим текстом или зависнуть. Это по желанию пользователя при клике на текстовое поле или будет висеть. 

Выходит на данном этапе разработки  пользователя только один выбор.
Почему:
Хотел в будущем добавить модальное окно с кнопками **ОК** и **Отмена**  и по событию **Esc** **Enter**
И после выбора приложение дальше работать.

2020-12-06 09:59 UTC, bringmetheaugust commented on src/js/temp-helpers-dev.js
> +// но необходимы для тестирования текущих разработок.
> Тогда, поместить в дев?
по желанию.
создай папку/файлик **utils_dev** и пиздец

2020-12-06 10:01 UTC, VSerj commented on src/js/timer.js
> +  }
Думал, так читабельней.

2020-12-06 10:08 UTC, VSerj commented on src/js/makeElem.js
> +export function makeElem({
с неймингом еще тяжело

2020-12-06 10:49 UTC, bringmetheaugust commented on src/js/text-from-api.js
> +  states.isLoading = false;
ок.
тогда просто надо решить проблему с тем, что в случае ошибки запроса, прелоадер переставал работать.
а то текстовое оповещение об ошибке есть, а прелоадер продолжает работать

2020-12-06 10:50 UTC, bringmetheaugust commented
все вопросы решены.
жду исправления всех минорных недочетов

2020-12-06 11:32 UTC, VSerj commented on src/js/start-stop.js
> +  // Для проверки и удаления подсказки, если она активна.
Если  выходит за рамки 80 символом?

2020-12-07 05:02 UTC, bringmetheaugust approved these changes

2020-12-07 05:02 UTC, bringmetheaugust commented on src/js/timer.js
> +  // установка времени в таймер после загрузки страницы.
здесь опять коммент описывает одну строку кода, надо писать его в той же строке

2020-12-07 05:02 UTC, bringmetheaugust commented on src/js/timer.js
> +  // Если активна кнопка старт, изменять значение таймера запрещено.
опять коммент не в одной строке

2020-12-07 05:03 UTC, merged