Dev statistics
VSerj/Type-faster pull request #14
Opened 2020-12-12 17:58 UTC by VSerj

Добавлены методы и поля для работы из статистикой:
- простой подсчет средней скорости печати каждую секунду из колбэком (для индикации).
- форматирование даты в строку;
- добавление корректных символов
- создание шаблона HTML для текущей статистики (если надо показать в UI);
- добавление статистики в localStorage;
- очистка текущей статистики;

Разработан простой вывод статистики на экран с помощью модального окна по нажатию на кнопку Статистики.
И возможность очистить.

 В состоянии тестирования добавлен  логика для индикатора скорости печати и UI .

Поправлены некоторые критичные баги: добавление символов и ошибка вывода модального окна, если не была инициализирована печать и нажата кнопка Стоп

2020-12-13 07:30 UTC, bringmetheaugust commented
что за коммент к коммиту `some fix`?..

2020-12-13 07:47 UTC, bringmetheaugust commented
модуль `statistics.js` необычно неализован, а именно в виде готового объекта `stats`.
по всем канонам надо было это через класс сделать, чтобы он как раз создавал такой объект + все методы вынести в прототип.
но с другой стороны у нас создается только 1 объект, так что и в классе особого смысла и нет.

2020-12-13 08:00 UTC, bringmetheaugust approved these changes
всё работает.
лайк, репост, подписка на канал

2020-12-13 08:15 UTC, bringmetheaugust requested changes
немного переделать

2020-12-13 08:15 UTC, bringmetheaugust commented on src/js/statistics.js
> +  },
тут ты слишком намудрил.
у класса `Date` есть много методов, чтобы получить удобный нам формат даты и это лишает нас потребности писать свои методы.
это надо переделать

2020-12-13 08:23 UTC, bringmetheaugust commented on src/js/statistics.js
> +  },
и сразу совет:
* если нам нужно взять текущую дату, чтобы потом ею оперировать (использовать, форматировать, передавать и т.д), то лучше хранить эту дату как число в виде миллисекунд (через `Date.now()`)
* если же нам надо получить дату и мы сразу знаем, что мы не будем её как-то форматировать, то можно сразу смело её брать в виде строки

2020-12-13 09:40 UTC, VSerj commented on src/js/statistics.js
> +  },
new Date().toLocaleString() использовать такой метод?

2020-12-13 09:44 UTC, VSerj commented on src/js/typing.js
>      return currentCharSpan.nextElementSibling.classList.add('current'); // Следующий символ
Тоже думал, после ревью посмотрел, что это живая коллекция 👍

2020-12-13 09:47 UTC, VSerj commented on src/js/statistics-btn.js
> +        document.querySelector('.modal-content').innerHTML = 'Готово!';">Очистить все</button>`
не продумал заранее возможность модификации кнопок для модального окна

2020-12-13 09:53 UTC, VSerj commented
> что за коммент к коммиту `some fix`?..

Было опрометчиво с моей стороны.

2020-12-13 09:58 UTC, VSerj commented
> модуль `statistics.js` необычно реализован, а именно в виде готового объекта `stats`.
> по всем канонам надо было это через класс сделать, чтобы он как раз создавал такой объект + все методы вынести в прототип.
> но с другой стороны у нас создается только 1 объект, так что и в классе особого смысла и нет, так что можешь оставить как есть

решил, что приложение небольшое, и блага прототипного наследование использоваться в этом случае не будут.

2020-12-13 10:19 UTC, bringmetheaugust commented on src/js/statistics-btn.js
> +        document.querySelector('.modal-content').innerHTML = 'Готово!';">Очистить все</button>`
ну пусть так пока будет

2020-12-13 10:28 UTC, bringmetheaugust commented on src/js/statistics.js
> +  },
у класса `Date` много всяких способов, но для начала можно попробовать и `.toLocaleString()`, так как он имеет тонкую настройку с помощью опций `options`, который передается как аргумент

2020-12-13 22:31 UTC, VSerj commented
> у класса `Date` много всяких способов, но для начала можно попробовать и `.toLocaleString()`, так как он имеет тонкую настройку с помощью опций `options`, который передается как аргумент

`.toLocaleString()` применил. Смотрел опции, но думаю для начала  base вариант сойдет. Почти идентичен изначальному коду для формата. Спасибо за подсказку 👍 

> здесь, конечно, жесткое решение, а именно вешать инлайн обработчик через `innerHTML`.
> но тебе виднее

Убрать инлайн-обработчик. Для этого немного изменил код для модального окна.

Далее обнаружил критичный баг с модальным окном. Который стал очевиден в режиме загрузки своего текста , когда недоступен Фиш АПИ.  Поправил.

2020-12-13 22:49 UTC, VSerj commented on src/js/typing.js
> +  if (states.isLoading) return;
Если нажму кнопку старт, "вешается" обработчик нажатие кнопки, но надо дождаться текста, для обработки статистики.

2020-12-13 22:55 UTC, VSerj commented on src/js/modal-window.js
> -  };
Не логичное условие: удалял модальное окно из HTML, но оставлял обработчик для удаления модалки. 
Обработчики могли накапливаться, что приводило к багам.

2020-12-13 22:58 UTC, VSerj commented on src/js/modal-window.js
> -function removeModalWindow(target, helpHandlerOk, helpHandlerClose) {
Перенес объявление во внутрь showModalWindow

2020-12-14 06:02 UTC, bringmetheaugust commented
всё, изменения больше не будет?

2020-12-14 06:54 UTC, VSerj commented
> всё, изменений больше не будет?

Не будет

2020-12-14 09:40 UTC, bringmetheaugust approved these changes

2020-12-14 09:40 UTC, bringmetheaugust commented on src/js/modal-window.js
> +  return (states.isModalWindow = true);
верю, что здесь всё рабочее и не просто так написано, но объясни что делает выражение `return (states.isModalWindow = true)`

2020-12-14 09:42 UTC, merged

2020-12-14 13:15 UTC, VSerj commented on src/js/modal-window.js
> +  return (states.isModalWindow = true);
эти выражения можно будет удалить.
Начальный замыл был: в предотвращении открытия нескольких модальных окон используя данное свойство для проверки. Для чего в выражении оператор **return** и не вспомню.

2020-12-14 14:28 UTC, bringmetheaugust commented on src/js/modal-window.js
> +  return (states.isModalWindow = true);
я как раз за `return` и интересовался